# Generated by Django 6.0.2 on 2026-10-06 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, default='', max_length=100)),
                ('client_version', models.CharField(blank=True, default='', max_length=50)),
                ('protocol_version', models.CharField(blank=True, default='', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('tool_calls', models.JSONField(blank=True, default=dict)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='agents.mcptoken')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
