# Generated by Django 6.0.2 on 2026-10-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_fxrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fxrate',
            name='source',
            field=models.CharField(choices=[('ecb', 'ECB via Frankfurter'), ('erapi', 'Exchange Rate API')], default='ecb', max_length=10),
        ),
        migrations.CreateModel(
            name='ManualFxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('units_per_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('rate_to_usd', models.DecimalField(decimal_places=8, max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_fx_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
    ]
