# Generated by Django 6.0.2 on 2026-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_category_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual'), ('biennial', 'Biennial')], max_length=20),
        ),
    ]
