# Generated by Django 6.0.2 on 2026-04-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_add_biannual_biennial_recurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='recurrence_day',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurrence_month',
        ),
    ]
