# Generated by Django 6.0.2 on 2026-10-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agentimportconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentImportConfig',
        ),
    ]
