# Generated by Django 6.0.2 on 2026-10-06 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_mcpsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mcp', 'MCP agent'), ('import', 'Agent import'), ('system', 'System')], default='web', max_length=10)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('entity_type', models.CharField(db_index=True, max_length=30)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('entity_label', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='agents.mcpsession')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='agents.mcptoken')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='activity_ac_entity__564be5_idx')],
            },
        ),
    ]
