# Generated by Django 6.0.2 on 2026-10-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('mcp', 'MCP agent'), ('system', 'System')], default='web', max_length=10),
        ),
    ]
